/* eslint-disable */
// Generated by scripts/generate-sandbox-toolchains.mjs from the Sandbox image's
// toolchain manifests. Do not edit by hand.
// prettier-ignore
export const GENERATED_SANDBOX_TOOLCHAINS = [
  {
    "id": "626d7ceeef0019d0e4d0aa770ee2305d51a22b4c6c61a5bbd56222337115f680",
    "framework": "tanstack-start",
    "root": "/opt/morph-toolchain/tanstack-start-1.168",
    "manifestFormat": 1,
    "packageJsonSha256": "c60ddac47799f05e19be93c5b72c9c0c3ed97fffcd29dcf55d49714c38f0ed12",
    "packageLockSha256": "093fdb1a52e49249e201955b68ae1bebbc8cfb198cb6594e9a54f851af3aad6b",
    "installedPositions": 174,
    "directDependencies": {
      "@cloudflare/vite-plugin": "1.62.4",
      "@tailwindcss/vite": "4.1.17",
      "@tanstack/react-router": "1.170.18",
      "@tanstack/react-start": "1.168.32",
      "@tanstack/router-plugin": "1.168.23",
      "@vitejs/plugin-react": "5.2.0",
      "class-variance-authority": "0.7.1",
      "clsx": "2.1.1",
      "lucide-react": "0.544.0",
      "react": "19.2.1",
      "react-dom": "19.2.1",
      "tailwind-merge": "3.4.0",
      "tailwindcss": "4.1.17",
      "vite": "7.3.5",
      "wrangler": "4.146.0"
    },
    "node": "v22.23.2",
    "npm": "10.9.8",
    "baseImage": "docker.io/cloudflare/sandbox:0.12.7@sha256:6d741713aef266e8ae0831a5709c6f2d7b77b4952ac79b549f4f4e380af86fbe",
    "platform": {
      "arch": "x64",
      "libc": "glibc 2.35",
      "os": "linux"
    }
  },
  {
    "id": "5ad55f6bc34660e95f536c9c3b873a3382a1a4de614d341181f5763531787feb",
    "framework": "astro",
    "root": "/opt/morph-toolchain/astro-7.3",
    "manifestFormat": 1,
    "packageJsonSha256": "c8f7eee0c388a4879285291fa09c7710fd3fa008f059ce1f1c3f95b009bb2e1d",
    "packageLockSha256": "ef3b4738a84c79ad3d4bf9b8c5f1abeb91d24f2c397bf2d3986f13f0891fa42a",
    "installedPositions": 245,
    "directDependencies": {
      "@astrojs/cloudflare": "14.3.3",
      "@astrojs/compiler-rs": "0.5.1",
      "@astrojs/react": "7.0.0",
      "@cloudflare/vite-plugin": "1.62.5",
      "astro": "7.3.5",
      "react": "19.3.0",
      "react-dom": "19.3.0",
      "vite": "8.3.3",
      "wrangler": "4.147.0"
    },
    "node": "v22.23.2",
    "npm": "10.9.8",
    "baseImage": "docker.io/cloudflare/sandbox:0.12.7@sha256:6d741713aef266e8ae0831a5709c6f2d7b77b4952ac79b549f4f4e380af86fbe",
    "platform": {
      "arch": "x64",
      "libc": "glibc 2.35",
      "os": "linux"
    }
  }
] as const;
// prettier-ignore
export const GENERATED_SANDBOX_PLATFORM_TOOLS = {
  "id": "b974af814278fd4a932d2a84b5cede558d5abd1375611b309076c92aef4096dc",
  "framework": "platform",
  "root": "/opt/morph-platform",
  "manifestFormat": 1,
  "packageJsonSha256": "ebf1c6b046ef7fb3a3cb126fa200eb61a7e777ed49f7a689dfe2f297d55486b4",
  "packageLockSha256": "2405585cd4243e9363d55bdcf61014efca55a98dc4d92be0b4b81b8efa53fc1b",
  "installedPositions": 40,
  "directDependencies": {
    "wrangler": "4.146.0"
  },
  "node": "v22.23.2",
  "npm": "10.9.8",
  "baseImage": "docker.io/cloudflare/sandbox:0.12.7@sha256:6d741713aef266e8ae0831a5709c6f2d7b77b4952ac79b549f4f4e380af86fbe",
  "platform": {
    "arch": "x64",
    "libc": "glibc 2.35",
    "os": "linux"
  }
} as const;
