// @vitest-environment node
import { describe, expect, it } from "vitest";
import {
  describeSvgRefusal,
  SVG_VALIDATOR_VERSION,
  validateSvg,
  type SvgRefusal,
} from "./svg-validation";

const bytes = (text: string) => new TextEncoder().encode(text);
const svg = (body: string, attributes = "") =>
  `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"${attributes}>${body}</svg>`;

/** Files a site legitimately uses, in the shapes the common tools write. */
const ACCEPTED: Record<string, string> = {
  "a stroke icon": svg(
    '<path d="M5 12h14"/><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
  ),
  "a gradient fill": svg(
    '<defs><linearGradient id="g" x1="0" x2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#000" stop-opacity=".5"/></linearGradient></defs><rect width="24" height="24" fill="url(#g)" style="stroke: url( \'#g\' ); opacity:.9"/>',
  ),
  "an Inkscape export": `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:cc="http://creativecommons.org/ns#" xmlns:dc="http://purl.org/dc/elements/1.1/" width="210mm" height="297mm" inkscape:version="1.3" sodipodi:docname="logo.svg">
  <sodipodi:namedview id="namedview1" pagecolor="#ffffff" inkscape:zoom="0.5"/>
  <metadata><rdf:RDF><cc:Work rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/></cc:Work></rdf:RDF></metadata>
  <g inkscape:label="Layer 1" inkscape:groupmode="layer" id="layer1"><rect style="fill:#ff0000;stroke-width:0.26" width="50" height="50" x="10" y="10"/></g>
</svg>`,
  "an Illustrator export": `<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#231F20;}
	.st1{fill:url(#SVGID_1_);}
</style>
<title>Logo</title>
<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="100" y2="100"><stop offset="0" style="stop-color:#FFFFFF"/></linearGradient>
<path class="st0" d="M10,10h80v80H10z"/><circle class="st1" cx="50" cy="50" r="20"/>
</svg>`,
  "a Figma export with a filter and clip": svg(
    '<g clip-path="url(#clip0)" filter="url(#f0)"><rect width="24" height="24" rx="4" fill="#2563EB"/></g><defs><filter id="f0" x="0" y="0" width="24" height="24" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="1"/><feGaussianBlur stdDeviation="1"/><feBlend in2="BackgroundImageFix" result="shadow"/></filter><clipPath id="clip0"><rect width="24" height="24"/></clipPath></defs>',
  ),
  "a spinner animation": svg(
    '<circle cx="12" cy="12" r="10" stroke="#000" fill="none" stroke-dasharray="30 60"><animateTransform attributeName="transform" type="rotate" from="0 12 12" to="360 12 12" dur="1s" repeatCount="indefinite"/><animate attributeName="stroke-opacity" values="1;.3;1" dur="1s" repeatCount="indefinite"/></circle>',
  ),
  "an embedded raster image": svg(
    '<image width="24" height="24" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="/>',
  ),
  "a tool's own attributes in its own namespace": svg(
    '<rect width="4" height="4" tool:layer="Background" tool:locked="true" xmlns:tool="urn:example:drawing-tool"/>',
  ),
  "a Graphviz export naming the W3C SVG DTD": `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz -->
${svg('<g id="graph0" class="graph"><polygon fill="white" points="0,0 10,0 10,10"/></g>')}`,
  "reuse by fragment, text and CDATA style": svg(
    '<style><![CDATA[ text { font: 12px sans-serif; } ]]></style><defs><symbol id="s"><path d="M0 0h1v1z"/></symbol></defs><use href="#s"/><use xlink:href="#s" x="4"/><text x="2" y="20">Hi <tspan fill="red">there</tspan></text>',
  ),
};

/** What an attacker would put in an SVG, one way each, and the reason it fails. */
const REFUSED: Record<string, [string, SvgRefusal]> = {
  "a script element": [svg("<script>alert(1)</script>"), "forbidden-element"],
  "an event handler": [svg("", ' onload="alert(1)"'), "event-handler"],
  "an event handler in another case": [
    svg('<rect OnClick="alert(1)"/>'),
    "event-handler",
  ],
  "foreign content": [
    svg(
      '<foreignObject><div xmlns="http://www.w3.org/1999/xhtml"><img src="x" onerror="alert(1)"/></div></foreignObject>',
    ),
    "forbidden-element",
  ],
  "XHTML without foreignObject": [
    svg(
      '<html:iframe xmlns:html="http://www.w3.org/1999/xhtml" src="https://x"/>',
    ),
    "foreign-namespace",
  ],
  "a javascript: link": [
    svg('<a xlink:href="javascript:alert(1)"><rect width="9" height="9"/></a>'),
    "forbidden-element",
  ],
  "an external use": [
    svg('<use href="https://evil.test/x.svg#a"/>'),
    "external-reference",
  ],
  "an external image": [
    svg('<image href="https://tracker.test/p.png"/>'),
    "external-reference",
  ],
  "an HTML data URL as an image": [
    svg('<image href="data:text/html,&lt;script&gt;alert(1)&lt;/script&gt;"/>'),
    "external-reference",
  ],
  "an SVG data URL as an image": [
    svg('<image href="data:image/svg+xml;base64,PHN2Zy8+"/>'),
    "external-reference",
  ],
  "an external filter image": [
    svg('<filter id="f"><feImage href="https://x.test/a.png"/></filter>'),
    "external-reference",
  ],
  "a link set by animation": [
    svg('<set attributeName="href" to="javascript:alert(1)"/>'),
    "unsafe-animation",
  ],
  "an xlink:href set by animation": [
    svg('<animate attributeName="xlink:href" values="javascript:alert(1)"/>'),
    "unsafe-animation",
  ],
  "an event handler set by animation": [
    svg('<set attributeName="onmouseover" to="alert(1)"/>'),
    "unsafe-animation",
  ],
  "a CSS import": [
    svg("<style>@import url(https://evil.test/a.css);</style>"),
    "unsafe-css",
  ],
  "a CSS url in a stylesheet": [
    svg("<style>rect { fill: url(https://evil.test/x.svg#p) }</style>"),
    "external-reference",
  ],
  "a CSS url in a style attribute": [
    svg("<rect style=\"background: url('https://evil.test/beacon')\"/>"),
    "external-reference",
  ],
  "a url in a presentation attribute": [
    svg('<rect fill="url(https://evil.test/x.svg#g)"/>'),
    "external-reference",
  ],
  "a DOCTYPE with entities": [
    `<?xml version="1.0"?><!DOCTYPE svg [<!ENTITY x "boom">]>${svg("<text>&x;</text>")}`,
    "doctype",
  ],
  "the W3C DTD with an internal subset": [
    `<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" [<!ENTITY x "boom">]>${svg("<text>&x;</text>")}`,
    "doctype",
  ],
  "a DOCTYPE naming another DTD": [
    `<!DOCTYPE svg SYSTEM "https://evil.test/x.dtd">${svg("")}`,
    "doctype",
  ],
  "an XML stylesheet": [
    `<?xml version="1.0"?><?xml-stylesheet href="https://evil.test/a.xsl"?>${svg("")}`,
    "processing-instruction",
  ],
  "xml:base": [
    svg('<g xml:base="https://evil.test/"><use href="#a"/></g>'),
    "external-reference",
  ],
  "a root that is not svg": [
    '<html xmlns="http://www.w3.org/1999/xhtml"><body/></html>',
    "not-svg",
  ],
  "svg outside the SVG namespace": ["<svg><rect/></svg>", "not-svg"],
  "malformed XML": [
    '<svg xmlns="http://www.w3.org/2000/svg"><g></svg>',
    "not-xml",
  ],
  "an unknown SVG-namespace element": [
    svg("<handler>x</handler>"),
    "forbidden-element",
  ],
  "an element in an unknown namespace": [
    svg('<x:thing xmlns:x="urn:example"/>'),
    "foreign-namespace",
  ],
  "an event handler in an unknown namespace": [
    svg('<rect x:onload="1" xmlns:x="urn:example"/>'),
    "event-handler",
  ],
  "an external reference in the XLink namespace under another prefix": [
    svg(
      '<use l:href="https://evil.test/x.svg#a" xmlns:l="http://www.w3.org/1999/xlink"/>',
    ),
    "external-reference",
  ],
  "a mozilla binding": [
    svg('<rect style="-moz-binding: url(#x)"/>'),
    "unsafe-css",
  ],
};

describe("validateSvg", () => {
  for (const [name, source] of Object.entries(ACCEPTED)) {
    it(`accepts ${name}`, () => {
      const result = validateSvg(bytes(source));
      expect(result, result.ok ? "" : describeSvgRefusal(result)).toEqual({
        ok: true,
        validatorVersion: SVG_VALIDATOR_VERSION,
      });
    });
  }

  for (const [name, [source, reason]] of Object.entries(REFUSED)) {
    it(`refuses ${name}, as ${reason}`, () => {
      const result = validateSvg(bytes(source));
      expect(result.ok).toBe(false);
      if (result.ok) return;
      expect(result.reason).toBe(reason);
      expect(result.validatorVersion).toBe(SVG_VALIDATOR_VERSION);
    });
  }

  it("refuses bytes that are not UTF-8", () => {
    const result = validateSvg(new Uint8Array([0x3c, 0x73, 0xff, 0xfe]));
    expect(result).toMatchObject({ ok: false, reason: "not-utf8" });
  });

  it("says what to change and where, and never that it fixed anything", () => {
    const result = validateSvg(
      bytes(`${svg("")}`.replace("<svg ", '<svg onload="x" ')),
    );
    if (result.ok) throw new Error("expected a refusal");
    const message = describeSvgRefusal(result);
    expect(message).toContain("onload");
    expect(message).toContain("Edit the original file");
  });
});
