import { sql } from "drizzle-orm";
import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { metadata, timestamps } from "./columns";

/**
 * Invitations to the dashboard.
 *
 * Medusa's User Module is two tables, `user` and `invite`. Only the second is
 * translated: Better Auth already owns `users`, `sessions` and `accounts`, and
 * a second user table would be two places to ask who someone is.
 *
 * Kept out of `auth.schema.ts` deliberately — that file is generated by
 * `pnpm auth:update` and hand-edits there are lost on the next run (rules.md
 * §4).
 *
 * `token` is a hash, not the token in the emailed link, for the same reason
 * `apiKeys.token` is: a leaked database must not let anyone accept an
 * outstanding invitation.
 */
export const invites = sqliteTable(
  "invites",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    /** A hash of the invitation token. Never the token itself. */
    token: text("token").notNull(),
    accepted: integer("accepted", { mode: "boolean" }).notNull().default(false),
    expiresAt: text("expires_at").notNull(),
    metadata: metadata(),
    ...timestamps,
  },
  (table) => [
    // One outstanding invitation per address; re-inviting replaces it.
    uniqueIndex("invites_active_email_unique")
      .on(table.email)
      .where(sql`${table.deletedAt} IS NULL`),
    index("invites_token_active_idx")
      .on(table.token)
      .where(sql`${table.deletedAt} IS NULL`),
  ],
);
