// @vitest-environment node
/**
 * Which identity markers a component has to write by hand: none.
 *
 * The interpreter runs a component's `map()` itself, so it knows which row it
 * is on and derives `items.2.title` unasked. The rule against hand-written
 * `data-*` rests on that being true of every binding a starter uses, which is
 * worth an assertion rather than a memory — the last exception was a grouped
 * image read through a fallback chain, and it only survived because the
 * inference stopped at optional chaining.
 */
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { renderSafeThemeComponent } from "@/components/storefront/safe-theme-component-renderer";
import { renderLivePreviewComponent } from "@/lib/test-utils/live-preview-render";
import { STARTER_THEME_CATALOG_FILES } from "./starter-theme-catalog-files";
import { STARTER_THEME_FILES } from "./starter-theme-files";

const files = STARTER_THEME_FILES.map((file) => ({
  path: file.path,
  content: file.content,
}));

const rows = {
  items: [
    {
      title: "A",
      caption: "a",
      link: { href: "/a" },
      image: { src: "/a.png", alt: "a" },
    },
    {
      title: "B",
      caption: "b",
      link: { href: "/b" },
      image: { src: "/b.png", alt: "b" },
    },
  ],
};

function pathsFor(path: string, content?: string) {
  const used = content
    ? files.map((file) => (file.path === path ? { ...file, content } : file))
    : files;
  const result = renderSafeThemeComponent({
    files: used,
    sourcePath: path,
    props: rows,
  } as never) as { success: boolean; node: unknown };
  expect(result.success).toBe(true);
  const markup = renderToStaticMarkup(result.node as never);
  return [
    ...new Set(
      [...markup.matchAll(/data-storefront-field-path="([^"]*)"/g)].map(
        (m) => m[1],
      ),
    ),
  ].sort();
}

describe("row identity in the starter", () => {
  it("is derived, not authored, for the components that write nothing", () => {
    for (const file of files) {
      if (!file.path.startsWith("src/components/")) continue;
      expect(
        (file.content.match(/data-storefront-field-path/g) || []).length,
        `${file.path} writes more identity markers than it needs`,
      ).toBeLessThanOrEqual(1);
    }
  });

  it("still names every row of a repeated field", () => {
    const paths = pathsFor("src/components/CategoryShowcase.tsx");

    expect(paths).toContain("items.0.title");
    expect(paths).toContain("items.1.title");
    expect(paths).toContain("items.0.caption");
  });

  it("derives a grouped value read through a fallback chain", () => {
    // `item.image?.src ?? item.imageSrc ?? "…"`. The field is `image`: the
    // first step off the row, with the rest reaching inside the value it
    // holds and the fallbacks describing what to show when it is empty.
    expect(pathsFor("src/components/CategoryShowcase.tsx")).toContain(
      "items.0.image",
    );
  });

  it("writes no identity markers at all", () => {
    for (const file of files) {
      if (!file.path.startsWith("src/components/")) continue;
      expect(
        file.content,
        `${file.path} writes an identity marker the inference can produce`,
      ).not.toContain("data-storefront-field-path");
      expect(
        file.content,
        `${file.path} writes a content marker the inference can produce`,
      ).not.toMatch(/data-storefront-field\s*=/);
    }
  });
});

/**
 * The catalog ships from its own module, which is how it kept thirty-eight
 * hand-written `data-morph-node` attributes through every round that removed
 * them everywhere else: the guard above only ever walked `STARTER_THEME_FILES`.
 * Both sets are named here so a file cannot again be generated by a path no
 * assertion reaches.
 */
describe("every file Morph generates for Code mode", () => {
  it("names its elements without a hand-written data attribute", () => {
    for (const file of [
      ...STARTER_THEME_FILES,
      ...STARTER_THEME_CATALOG_FILES,
    ]) {
      expect(
        file.content.match(/data-(?:morph|storefront)-[a-z-]+/g) ?? [],
        `${file.path} writes a marker the compiler now derives`,
      ).toEqual([]);
    }
  });
});

/**
 * Row identity in the real React Live Preview. React runs the loop, so the
 * identity has to be written in before it does: that is the preview's source
 * pass, and these hold that it names every row the starter renders.
 */
describe("row identity in the starter, in real React", () => {
  async function livePathsFor(path: string, previewPass?: boolean) {
    const { html } = await renderLivePreviewComponent({
      files,
      sourcePath: path,
      props: rows,
      previewPass,
    });
    return [
      ...new Set(
        [...html.matchAll(/data-storefront-field-path="([^"]*)"/g)].map(
          (m) => m[1],
        ),
      ),
    ].sort();
  }

  it("still names every row of a repeated field", async () => {
    const paths = await livePathsFor("src/components/CategoryShowcase.tsx");

    expect(paths).toContain("items.0.title");
    expect(paths).toContain("items.1.title");
    expect(paths).toContain("items.0.caption");
  });

  it("derives a grouped value read through a fallback chain", async () => {
    expect(await livePathsFor("src/components/CategoryShowcase.tsx")).toContain(
      "items.0.image",
    );
  });

  it("names nothing without the preview's source pass", async () => {
    // The starter writes no identity itself (asserted above), so every path
    // found by the two tests before this one came from that pass.
    expect(
      await livePathsFor("src/components/CategoryShowcase.tsx", false),
    ).toEqual([]);
  });
});
