/* eslint-disable */
// Generated by scripts/generate-theme-package-types.mjs. Do not edit by hand.
// prettier-ignore
export const GENERATED_THEME_DEPENDENCY_VERSIONS = {
  "@cloudflare/vite-plugin": "1.50.0",
  "@tailwindcss/vite": "4.1.17",
  "@tanstack/react-router": "1.170.18",
  "@tanstack/react-start": "1.168.32",
  "@tanstack/router-plugin": "1.168.23",
  "@vitejs/plugin-react": "5.2.0",
  "class-variance-authority": "0.7.1",
  "clsx": "2.1.1",
  "lucide-react": "0.544.0",
  "react": "19.2.1",
  "react-dom": "19.2.1",
  "react-dom/client": "19.2.1",
  "react/jsx-dev-runtime": "19.2.1",
  "react/jsx-runtime": "19.2.1",
  "tailwind-merge": "3.4.0",
  "tailwindcss": "4.1.17",
  "vite": "7.2.7",
  "vite/modulepreload-polyfill": "7.2.7"
} as const;
// prettier-ignore
export const GENERATED_SANDBOX_DEPENDENCY_VERSIONS = {
  "@cloudflare/vite-plugin": "1.50.0",
  "@tailwindcss/vite": "4.1.17",
  "@tanstack/react-router": "1.170.18",
  "@tanstack/react-start": "1.168.32",
  "@tanstack/router-plugin": "1.168.23",
  "@vitejs/plugin-react": "5.2.0",
  "class-variance-authority": "0.7.1",
  "clsx": "2.1.1",
  "lucide-react": "0.544.0",
  "react": "19.2.1",
  "react-dom": "19.2.1",
  "tailwind-merge": "3.4.0",
  "tailwindcss": "4.1.17",
  "vite": "7.2.7"
} as const;
