/* eslint-disable */
// Generated by scripts/generate-theme-package-types.mjs. Do not edit by hand.
export type GeneratedThemePackageDeclaration = {
  readonly path: string;
  readonly content: string;
};

// prettier-ignore
export const GENERATED_THEME_PACKAGE_NAMES: readonly string[] = [];
// prettier-ignore
export const GENERATED_THEME_PACKAGE_DECLARATIONS: readonly GeneratedThemePackageDeclaration[] = [

];
