/* eslint-disable */
// Generated by scripts/generate-theme-package-types.mjs. Do not edit by hand.
export type GeneratedThemePackageDeclaration = {
  readonly path: string;
  readonly content: string;
};

// prettier-ignore
export const GENERATED_THEME_PACKAGE_NAMES: readonly string[] = ["react","react/jsx-runtime","react/jsx-dev-runtime","react-dom","react-dom/client","clsx","tailwind-merge","lucide-react","class-variance-authority","@tanstack/react-router","@tanstack/react-start"];
// prettier-ignore
export const GENERATED_THEME_APPROVED_DEPENDENCIES: readonly string[] = ["@cloudflare/vite-plugin","@tailwindcss/vite","@tanstack/react-router","@tanstack/react-start","@tanstack/router-plugin","@vitejs/plugin-react","class-variance-authority","clsx","lucide-react","react","react-dom","react-dom/client","react/jsx-dev-runtime","react/jsx-runtime","tailwind-merge","tailwindcss","vite","vite/modulepreload-polyfill"];
