import { isPlatformOwnedThemeBuildPath } from "@/lib/storefront/compiler/theme-start-toolchain";
import { THEME_CONTENT_MODULE_PATH } from "@/lib/storefront/theme-content-slots";
import { safeThemeFilePathSchema } from "@/lib/validations/storefront-theme-file";

/**
 * Extensions a Theme author may create.
 *
 * The build toolchain only understands these, so allowing anything else would
 * create a file that silently never reaches the artifact.
 */
const CREATABLE_EXTENSIONS = [".tsx", ".ts", ".css", ".json"] as const;

export type NewThemeFileResult =
  | { ok: true; path: string; content: string; mimeType: string }
  | { ok: false; message: string };

function extensionOf(path: string): string {
  const index = path.lastIndexOf(".");
  return index === -1 ? "" : path.slice(index).toLowerCase();
}

export function themeFileMimeType(path: string): string {
  switch (extensionOf(path)) {
    case ".tsx":
    case ".ts":
      return "text/typescript";
    case ".css":
      return "text/css";
    case ".json":
      return "application/json";
    default:
      return "text/plain";
  }
}

/** kebab-case identity used for the component's editor markers. */
function componentSlugFrom(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1).replace(/\.[^.]+$/, "");
  const slug = base
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return slug || "component";
}

function componentNameFrom(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1).replace(/\.[^.]+$/, "");
  const cleaned = base.replace(/[^a-zA-Z0-9]/g, " ").trim();
  const pascal = cleaned
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
  return /^[A-Za-z]/.test(pascal) ? pascal : `Component${pascal}`;
}

/**
 * Seed content for a newly created file.
 *
 * A new component is scaffolded with its own `contentFields` declaration so it
 * is editable in the Inspector immediately, without registering it anywhere.
 */
export function scaffoldThemeFile(path: string): string {
  const extension = extensionOf(path);
  if (extension === ".css") return "";
  if (extension === ".json") return "{}\n";
  if (extension === ".ts") return "export {};\n";

  const name = componentNameFrom(path);
  const slug = componentSlugFrom(path);
  // The editor locates selectable elements by `data-morph-node`, and binds a
  // rendered subtree to its section by `data-morph-section`. Scaffolding
  // without them produces a component that renders but can never be selected.
  return `export const contentFields = {
  heading: { type: "text", label: "Heading" },
} as const;

export type ${name}Props = {
  heading?: string;
};

export default function ${name}({ heading = "${name}" }: ${name}Props) {
  return (
    <section
      data-morph-section="${slug}"
      data-morph-node="${slug}-root"
      className="px-6 py-16"
    >
      <h2
        data-morph-node="${slug}-heading"
        data-morph-element="heading"
        className="text-2xl font-semibold"
      >
        {heading}
      </h2>
    </section>
  );
}
`;
}

/**
 * Validates a path the author typed before anything is written.
 *
 * Refuses the same shapes the storage boundary refuses, plus platform-owned
 * build files and paths that already exist, so a create can never overwrite
 * existing work or shadow a generated file.
 */
export function prepareNewThemeFile(
  rawPath: string,
  existingPaths: readonly string[],
): NewThemeFileResult {
  const normalized = (rawPath ?? "").trim().replace(/\\/g, "/").replace(/^\/+/, "");
  if (!normalized) {
    return { ok: false, message: "Enter a file path." };
  }

  const parsed = safeThemeFilePathSchema.safeParse(normalized);
  if (!parsed.success) {
    return {
      ok: false,
      message: parsed.error.issues[0]?.message ?? "Invalid file path.",
    };
  }
  const path = parsed.data;

  if (path.endsWith("/")) {
    return { ok: false, message: "Enter a file path, not a folder." };
  }

  const extension = extensionOf(path);
  if (!CREATABLE_EXTENSIONS.includes(extension as never)) {
    return {
      ok: false,
      message: `Only ${CREATABLE_EXTENSIONS.join(", ")} files can be created.`,
    };
  }

  if (isPlatformOwnedThemeBuildPath(path)) {
    return {
      ok: false,
      message: `"${path}" is generated by the build and cannot be authored.`,
    };
  }

  // Seeded and upgraded by the platform. Unlike build-generated files it does
  // reach the build, so it is refused here rather than at the build boundary.
  if (path === THEME_CONTENT_MODULE_PATH) {
    return {
      ok: false,
      message: `"${path}" is provided by Morph and cannot be replaced.`,
    };
  }

  if (existingPaths.some((existing) => existing.replace(/\\/g, "/") === path)) {
    return { ok: false, message: `"${path}" already exists.` };
  }

  return {
    ok: true,
    path,
    content: scaffoldThemeFile(path),
    mimeType: themeFileMimeType(path),
  };
}
