import { describe, expect, it } from "vitest";
import {
  prepareNewThemeFile,
  scaffoldThemeFile,
  themeFileMimeType,
} from "./new-theme-file";

const existing = ["src/components/Hero.tsx", "morph.theme.json"];

describe("prepareNewThemeFile", () => {
  it("accepts a component path and scaffolds an editable component", () => {
    const result = prepareNewThemeFile("src/components/Promo.tsx", existing);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.path).toBe("src/components/Promo.tsx");
    expect(result.mimeType).toBe("text/typescript");
    // Scaffolded with its own declaration so the Inspector can edit it right
    // away, with nothing to register anywhere.
    expect(result.content).toContain("export const contentFields");
    expect(result.content).toContain("export default function Promo");
    // Selection locates elements by these markers; a component scaffolded
    // without them renders but can never be selected in the editor.
    expect(result.content).toContain('data-morph-section="promo"');
    expect(result.content).toContain('data-morph-node="promo-root"');
    expect(result.content).toContain('data-morph-node="promo-heading"');
    expect(result.content).toContain('data-morph-element="heading"');
  });

  it("normalizes a leading slash and backslashes", () => {
    const result = prepareNewThemeFile("/src\\components\\Promo.tsx", existing);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.path).toBe("src/components/Promo.tsx");
  });

  it("refuses a path that already exists", () => {
    const result = prepareNewThemeFile("src/components/Hero.tsx", existing);
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.message).toContain("already exists");
  });

  it("refuses platform-generated build files", () => {
    for (const path of [
      "vite.config.ts",
      "src/routeTree.gen.ts",
      "wrangler.json",
      "__entry.tsx",
    ]) {
      const result = prepareNewThemeFile(path, existing);
      expect(result.ok, path).toBe(false);
      if (result.ok) return;
      expect(result.message).toContain("generated by the build");
    }
  });

  it("refuses replacing the platform-provided content module", () => {
    const result = prepareNewThemeFile("src/morph/content.ts", existing);
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.message).toContain("provided by Morph");
  });

  it("refuses traversal and unsafe paths", () => {
    for (const path of [
      "../secret.tsx",
      "src/../../etc/passwd.tsx",
      "src/node_modules/x.tsx",
      "src/comp onent.tsx",
    ]) {
      expect(prepareNewThemeFile(path, existing).ok, path).toBe(false);
    }
  });

  it("refuses extensions the build toolchain would ignore", () => {
    for (const path of ["src/notes.md", "src/image.png", "src/script.js"]) {
      const result = prepareNewThemeFile(path, existing);
      expect(result.ok, path).toBe(false);
      if (result.ok) return;
      expect(result.message).toContain("can be created");
    }
  });

  it("refuses an empty path or a folder", () => {
    expect(prepareNewThemeFile("", existing).ok).toBe(false);
    expect(prepareNewThemeFile("   ", existing).ok).toBe(false);
    expect(prepareNewThemeFile("src/components/", existing).ok).toBe(false);
  });
});

describe("scaffoldThemeFile", () => {
  it("derives a valid component name from the filename", () => {
    expect(scaffoldThemeFile("src/components/promo-banner.tsx")).toContain(
      "function PromoBanner",
    );
  });

  it("derives kebab-case editor markers for any filename style", () => {
    const fromPascal = scaffoldThemeFile("src/components/PromoBanner.tsx");
    expect(fromPascal).toContain('data-morph-section="promo-banner"');
    expect(fromPascal).toContain('data-morph-node="promo-banner-root"');

    const fromKebab = scaffoldThemeFile("src/components/promo-banner.tsx");
    expect(fromKebab).toContain('data-morph-section="promo-banner"');
  });

  it("produces empty or minimal seeds for non-component files", () => {
    expect(scaffoldThemeFile("src/styles/extra.css")).toBe("");
    expect(scaffoldThemeFile("data.json")).toBe("{}\n");
    expect(scaffoldThemeFile("src/util.ts")).toBe("export {};\n");
  });
});

describe("themeFileMimeType", () => {
  it("maps each creatable extension", () => {
    expect(themeFileMimeType("a.tsx")).toBe("text/typescript");
    expect(themeFileMimeType("a.ts")).toBe("text/typescript");
    expect(themeFileMimeType("a.css")).toBe("text/css");
    expect(themeFileMimeType("a.json")).toBe("application/json");
  });
});
