import { isPlatformOwnedThemeBuildPath } from "@/lib/storefront/compiler/theme-start-toolchain";
import { safeThemeFilePathSchema } from "@/lib/validations/storefront-theme-file";

export type ThemeFileRenameResult =
  | { ok: true; path: string }
  | { ok: false; message: string };

/** Validates an inline file name while keeping Move as a separate operation. */
export function prepareThemeFileRename(
  rawName: string,
  originalPath: string,
  existingPaths: readonly string[],
): ThemeFileRenameResult {
  const name = rawName.trim();
  if (!name) return { ok: false, message: "Enter a file name." };
  if (name.includes("/") || name.includes("\\")) {
    return { ok: false, message: "File name cannot contain path separators." };
  }

  const slash = originalPath.lastIndexOf("/");
  const parent = slash < 0 ? "" : originalPath.slice(0, slash);
  const candidate = parent ? `${parent}/${name}` : name;
  const parsed = safeThemeFilePathSchema.safeParse(candidate);
  if (!parsed.success) {
    return {
      ok: false,
      message: parsed.error.issues[0]?.message ?? "Invalid file name.",
    };
  }

  const path = parsed.data;
  if (isPlatformOwnedThemeBuildPath(path)) {
    return {
      ok: false,
      message: `"${path}" is generated by the build and cannot be authored.`,
    };
  }
  if (path !== originalPath && existingPaths.includes(path)) {
    return { ok: false, message: `"${path}" already exists.` };
  }

  return { ok: true, path };
}
