/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BackendRouteImport } from './routes/_backend'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackendDashboardRouteImport } from './routes/_backend/dashboard'
import { Route as BackendAuthRouteImport } from './routes/_backend/_auth'
import { Route as BackendDashboardIndexRouteImport } from './routes/_backend/dashboard/index'
import { Route as BackendDashboardSlugRouteImport } from './routes/_backend/dashboard/$slug'
import { Route as BackendAuthSignInRouteImport } from './routes/_backend/_auth/sign-in'
import { Route as BackendAuthResetPasswordRouteImport } from './routes/_backend/_auth/reset-password'
import { Route as BackendAuthCreateFirstAdminRouteImport } from './routes/_backend/_auth/create-first-admin'
import { Route as BackendDashboardSettingsIndexRouteImport } from './routes/_backend/dashboard/settings/index'
import { Route as BackendAuthResetPasswordIndexRouteImport } from './routes/_backend/_auth/reset-password.index'
import { Route as BackendDashboardSettingsSlugRouteImport } from './routes/_backend/dashboard/settings/$slug'
import { Route as BackendApiAuthSplatRouteImport } from './routes/_backend/api/auth/$'
import { Route as BackendAuthResetPasswordVerifyRouteImport } from './routes/_backend/_auth/reset-password.verify'

const BackendRoute = BackendRouteImport.update({
  id: '/_backend',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackendDashboardRoute = BackendDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BackendRoute,
} as any)
const BackendAuthRoute = BackendAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => BackendRoute,
} as any)
const BackendDashboardIndexRoute = BackendDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackendDashboardRoute,
} as any)
const BackendDashboardSlugRoute = BackendDashboardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BackendDashboardRoute,
} as any)
const BackendAuthSignInRoute = BackendAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => BackendAuthRoute,
} as any)
const BackendAuthResetPasswordRoute =
  BackendAuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => BackendAuthRoute,
  } as any)
const BackendAuthCreateFirstAdminRoute =
  BackendAuthCreateFirstAdminRouteImport.update({
    id: '/create-first-admin',
    path: '/create-first-admin',
    getParentRoute: () => BackendAuthRoute,
  } as any)
const BackendDashboardSettingsIndexRoute =
  BackendDashboardSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => BackendDashboardRoute,
  } as any)
const BackendAuthResetPasswordIndexRoute =
  BackendAuthResetPasswordIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BackendAuthResetPasswordRoute,
  } as any)
const BackendDashboardSettingsSlugRoute =
  BackendDashboardSettingsSlugRouteImport.update({
    id: '/settings/$slug',
    path: '/settings/$slug',
    getParentRoute: () => BackendDashboardRoute,
  } as any)
const BackendApiAuthSplatRoute = BackendApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => BackendRoute,
} as any)
const BackendAuthResetPasswordVerifyRoute =
  BackendAuthResetPasswordVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => BackendAuthResetPasswordRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof BackendDashboardRouteWithChildren
  '/create-first-admin': typeof BackendAuthCreateFirstAdminRoute
  '/reset-password': typeof BackendAuthResetPasswordRouteWithChildren
  '/sign-in': typeof BackendAuthSignInRoute
  '/dashboard/$slug': typeof BackendDashboardSlugRoute
  '/dashboard/': typeof BackendDashboardIndexRoute
  '/reset-password/verify': typeof BackendAuthResetPasswordVerifyRoute
  '/api/auth/$': typeof BackendApiAuthSplatRoute
  '/dashboard/settings/$slug': typeof BackendDashboardSettingsSlugRoute
  '/reset-password/': typeof BackendAuthResetPasswordIndexRoute
  '/dashboard/settings': typeof BackendDashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-first-admin': typeof BackendAuthCreateFirstAdminRoute
  '/sign-in': typeof BackendAuthSignInRoute
  '/dashboard/$slug': typeof BackendDashboardSlugRoute
  '/dashboard': typeof BackendDashboardIndexRoute
  '/reset-password/verify': typeof BackendAuthResetPasswordVerifyRoute
  '/api/auth/$': typeof BackendApiAuthSplatRoute
  '/dashboard/settings/$slug': typeof BackendDashboardSettingsSlugRoute
  '/reset-password': typeof BackendAuthResetPasswordIndexRoute
  '/dashboard/settings': typeof BackendDashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_backend': typeof BackendRouteWithChildren
  '/_backend/_auth': typeof BackendAuthRouteWithChildren
  '/_backend/dashboard': typeof BackendDashboardRouteWithChildren
  '/_backend/_auth/create-first-admin': typeof BackendAuthCreateFirstAdminRoute
  '/_backend/_auth/reset-password': typeof BackendAuthResetPasswordRouteWithChildren
  '/_backend/_auth/sign-in': typeof BackendAuthSignInRoute
  '/_backend/dashboard/$slug': typeof BackendDashboardSlugRoute
  '/_backend/dashboard/': typeof BackendDashboardIndexRoute
  '/_backend/_auth/reset-password/verify': typeof BackendAuthResetPasswordVerifyRoute
  '/_backend/api/auth/$': typeof BackendApiAuthSplatRoute
  '/_backend/dashboard/settings/$slug': typeof BackendDashboardSettingsSlugRoute
  '/_backend/_auth/reset-password/': typeof BackendAuthResetPasswordIndexRoute
  '/_backend/dashboard/settings/': typeof BackendDashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/create-first-admin'
    | '/reset-password'
    | '/sign-in'
    | '/dashboard/$slug'
    | '/dashboard/'
    | '/reset-password/verify'
    | '/api/auth/$'
    | '/dashboard/settings/$slug'
    | '/reset-password/'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-first-admin'
    | '/sign-in'
    | '/dashboard/$slug'
    | '/dashboard'
    | '/reset-password/verify'
    | '/api/auth/$'
    | '/dashboard/settings/$slug'
    | '/reset-password'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_backend'
    | '/_backend/_auth'
    | '/_backend/dashboard'
    | '/_backend/_auth/create-first-admin'
    | '/_backend/_auth/reset-password'
    | '/_backend/_auth/sign-in'
    | '/_backend/dashboard/$slug'
    | '/_backend/dashboard/'
    | '/_backend/_auth/reset-password/verify'
    | '/_backend/api/auth/$'
    | '/_backend/dashboard/settings/$slug'
    | '/_backend/_auth/reset-password/'
    | '/_backend/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackendRoute: typeof BackendRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_backend': {
      id: '/_backend'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BackendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_backend/dashboard': {
      id: '/_backend/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof BackendDashboardRouteImport
      parentRoute: typeof BackendRoute
    }
    '/_backend/_auth': {
      id: '/_backend/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BackendAuthRouteImport
      parentRoute: typeof BackendRoute
    }
    '/_backend/dashboard/': {
      id: '/_backend/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof BackendDashboardIndexRouteImport
      parentRoute: typeof BackendDashboardRoute
    }
    '/_backend/dashboard/$slug': {
      id: '/_backend/dashboard/$slug'
      path: '/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof BackendDashboardSlugRouteImport
      parentRoute: typeof BackendDashboardRoute
    }
    '/_backend/_auth/sign-in': {
      id: '/_backend/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof BackendAuthSignInRouteImport
      parentRoute: typeof BackendAuthRoute
    }
    '/_backend/_auth/reset-password': {
      id: '/_backend/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof BackendAuthResetPasswordRouteImport
      parentRoute: typeof BackendAuthRoute
    }
    '/_backend/_auth/create-first-admin': {
      id: '/_backend/_auth/create-first-admin'
      path: '/create-first-admin'
      fullPath: '/create-first-admin'
      preLoaderRoute: typeof BackendAuthCreateFirstAdminRouteImport
      parentRoute: typeof BackendAuthRoute
    }
    '/_backend/dashboard/settings/': {
      id: '/_backend/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof BackendDashboardSettingsIndexRouteImport
      parentRoute: typeof BackendDashboardRoute
    }
    '/_backend/_auth/reset-password/': {
      id: '/_backend/_auth/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof BackendAuthResetPasswordIndexRouteImport
      parentRoute: typeof BackendAuthResetPasswordRoute
    }
    '/_backend/dashboard/settings/$slug': {
      id: '/_backend/dashboard/settings/$slug'
      path: '/settings/$slug'
      fullPath: '/dashboard/settings/$slug'
      preLoaderRoute: typeof BackendDashboardSettingsSlugRouteImport
      parentRoute: typeof BackendDashboardRoute
    }
    '/_backend/api/auth/$': {
      id: '/_backend/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof BackendApiAuthSplatRouteImport
      parentRoute: typeof BackendRoute
    }
    '/_backend/_auth/reset-password/verify': {
      id: '/_backend/_auth/reset-password/verify'
      path: '/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof BackendAuthResetPasswordVerifyRouteImport
      parentRoute: typeof BackendAuthResetPasswordRoute
    }
  }
}

interface BackendAuthResetPasswordRouteChildren {
  BackendAuthResetPasswordVerifyRoute: typeof BackendAuthResetPasswordVerifyRoute
  BackendAuthResetPasswordIndexRoute: typeof BackendAuthResetPasswordIndexRoute
}

const BackendAuthResetPasswordRouteChildren: BackendAuthResetPasswordRouteChildren =
  {
    BackendAuthResetPasswordVerifyRoute: BackendAuthResetPasswordVerifyRoute,
    BackendAuthResetPasswordIndexRoute: BackendAuthResetPasswordIndexRoute,
  }

const BackendAuthResetPasswordRouteWithChildren =
  BackendAuthResetPasswordRoute._addFileChildren(
    BackendAuthResetPasswordRouteChildren,
  )

interface BackendAuthRouteChildren {
  BackendAuthCreateFirstAdminRoute: typeof BackendAuthCreateFirstAdminRoute
  BackendAuthResetPasswordRoute: typeof BackendAuthResetPasswordRouteWithChildren
  BackendAuthSignInRoute: typeof BackendAuthSignInRoute
}

const BackendAuthRouteChildren: BackendAuthRouteChildren = {
  BackendAuthCreateFirstAdminRoute: BackendAuthCreateFirstAdminRoute,
  BackendAuthResetPasswordRoute: BackendAuthResetPasswordRouteWithChildren,
  BackendAuthSignInRoute: BackendAuthSignInRoute,
}

const BackendAuthRouteWithChildren = BackendAuthRoute._addFileChildren(
  BackendAuthRouteChildren,
)

interface BackendDashboardRouteChildren {
  BackendDashboardSlugRoute: typeof BackendDashboardSlugRoute
  BackendDashboardIndexRoute: typeof BackendDashboardIndexRoute
  BackendDashboardSettingsSlugRoute: typeof BackendDashboardSettingsSlugRoute
  BackendDashboardSettingsIndexRoute: typeof BackendDashboardSettingsIndexRoute
}

const BackendDashboardRouteChildren: BackendDashboardRouteChildren = {
  BackendDashboardSlugRoute: BackendDashboardSlugRoute,
  BackendDashboardIndexRoute: BackendDashboardIndexRoute,
  BackendDashboardSettingsSlugRoute: BackendDashboardSettingsSlugRoute,
  BackendDashboardSettingsIndexRoute: BackendDashboardSettingsIndexRoute,
}

const BackendDashboardRouteWithChildren =
  BackendDashboardRoute._addFileChildren(BackendDashboardRouteChildren)

interface BackendRouteChildren {
  BackendAuthRoute: typeof BackendAuthRouteWithChildren
  BackendDashboardRoute: typeof BackendDashboardRouteWithChildren
  BackendApiAuthSplatRoute: typeof BackendApiAuthSplatRoute
}

const BackendRouteChildren: BackendRouteChildren = {
  BackendAuthRoute: BackendAuthRouteWithChildren,
  BackendDashboardRoute: BackendDashboardRouteWithChildren,
  BackendApiAuthSplatRoute: BackendApiAuthSplatRoute,
}

const BackendRouteWithChildren =
  BackendRoute._addFileChildren(BackendRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackendRoute: BackendRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
