/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSlugRouteImport } from './routes/dashboard/$slug'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthCreateFirstAdminRouteImport } from './routes/_auth/create-first-admin'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/_auth/reset-password.index'
import { Route as DashboardSettingsSlugRouteImport } from './routes/dashboard/settings/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthResetPasswordVerifyRouteImport } from './routes/_auth/reset-password.verify'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSlugRoute = DashboardSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreateFirstAdminRoute = AuthCreateFirstAdminRouteImport.update({
  id: '/create-first-admin',
  path: '/create-first-admin',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthResetPasswordRoute,
} as any)
const DashboardSettingsSlugRoute = DashboardSettingsSlugRouteImport.update({
  id: '/settings/$slug',
  path: '/settings/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordVerifyRoute = AuthResetPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthResetPasswordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/create-first-admin': typeof AuthCreateFirstAdminRoute
  '/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/sign-in': typeof AuthSignInRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/settings/$slug': typeof DashboardSettingsSlugRoute
  '/reset-password/': typeof AuthResetPasswordIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-first-admin': typeof AuthCreateFirstAdminRoute
  '/sign-in': typeof AuthSignInRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/settings/$slug': typeof DashboardSettingsSlugRoute
  '/reset-password': typeof AuthResetPasswordIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/create-first-admin': typeof AuthCreateFirstAdminRoute
  '/_auth/reset-password': typeof AuthResetPasswordRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/dashboard/$slug': typeof DashboardSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_auth/reset-password/verify': typeof AuthResetPasswordVerifyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/settings/$slug': typeof DashboardSettingsSlugRoute
  '/_auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/create-first-admin'
    | '/reset-password'
    | '/sign-in'
    | '/dashboard/$slug'
    | '/dashboard/'
    | '/reset-password/verify'
    | '/api/auth/$'
    | '/dashboard/settings/$slug'
    | '/reset-password/'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-first-admin'
    | '/sign-in'
    | '/dashboard/$slug'
    | '/dashboard'
    | '/reset-password/verify'
    | '/api/auth/$'
    | '/dashboard/settings/$slug'
    | '/reset-password'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/_auth/create-first-admin'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/dashboard/$slug'
    | '/dashboard/'
    | '/_auth/reset-password/verify'
    | '/api/auth/$'
    | '/dashboard/settings/$slug'
    | '/_auth/reset-password/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$slug': {
      id: '/dashboard/$slug'
      path: '/$slug'
      fullPath: '/dashboard/$slug'
      preLoaderRoute: typeof DashboardSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/create-first-admin': {
      id: '/_auth/create-first-admin'
      path: '/create-first-admin'
      fullPath: '/create-first-admin'
      preLoaderRoute: typeof AuthCreateFirstAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/reset-password/': {
      id: '/_auth/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthResetPasswordRoute
    }
    '/dashboard/settings/$slug': {
      id: '/dashboard/settings/$slug'
      path: '/settings/$slug'
      fullPath: '/dashboard/settings/$slug'
      preLoaderRoute: typeof DashboardSettingsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password/verify': {
      id: '/_auth/reset-password/verify'
      path: '/verify'
      fullPath: '/reset-password/verify'
      preLoaderRoute: typeof AuthResetPasswordVerifyRouteImport
      parentRoute: typeof AuthResetPasswordRoute
    }
  }
}

interface AuthResetPasswordRouteChildren {
  AuthResetPasswordVerifyRoute: typeof AuthResetPasswordVerifyRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthResetPasswordRouteChildren: AuthResetPasswordRouteChildren = {
  AuthResetPasswordVerifyRoute: AuthResetPasswordVerifyRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthResetPasswordRouteWithChildren =
  AuthResetPasswordRoute._addFileChildren(AuthResetPasswordRouteChildren)

interface AuthRouteChildren {
  AuthCreateFirstAdminRoute: typeof AuthCreateFirstAdminRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCreateFirstAdminRoute: AuthCreateFirstAdminRoute,
  AuthResetPasswordRoute: AuthResetPasswordRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardSlugRoute: typeof DashboardSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsSlugRoute: typeof DashboardSettingsSlugRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSlugRoute: DashboardSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsSlugRoute: DashboardSettingsSlugRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
